name: Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: macro-meal-planner
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Create virtual environment
      run: |
        python -m venv antenv
        source antenv/bin/activate
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
        
    - name: Prepare deployment
      run: |
        chmod +x startup.sh
        
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        startup-command: ./startup.sh
        
    - name: Configure Azure Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group macro-meal-planner-rg \
            --linux-fx-version "PYTHON|3.9" \
            --startup-file "startup.sh"
            
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group macro-meal-planner-rg \
            --settings \
            FLASK_APP=run.py \
            FLASK_ENV=production \
            PORT=8000 \
            WEBSITES_PORT=8000 \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            PYTHONPATH=/home/site/wwwroot \
            PYTHON_ENV=/home/site/wwwroot/antenv
