name: Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: macro-meal-planner
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn
        
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        
    - name: Configure Web App Settings
      run: |
        az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group macro-meal-planner-rg --linux-fx-version "PYTHON|3.9"
        az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group macro-meal-planner-rg --settings \
          FLASK_APP=run.py \
          FLASK_ENV=production \
          SCM_DO_BUILD_DURING_DEPLOYMENT=true \
          WEBSITE_WEBDEPLOY_USE_SCM=true
