name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main

env:
  NODE_VERSION: '18'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate PR
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Setup PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: test_user
          password: test_password
          database: test_db
          port: 5432

      - name: Run unit tests
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
          NEXTAUTH_SECRET: test-secret
          AUTH_GITHUB_ID: test-id
          AUTH_GITHUB_SECRET: test-secret
          OPENAI_API_KEY: test-key
        run: npm run test:unit

      - name: Build check
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: test-secret
          AUTH_GITHUB_ID: test-id
          AUTH_GITHUB_SECRET: test-secret
          OPENAI_API_KEY: test-key
        run: npm run build
