name: Deploy to Staging

on:
  push:
    branches: [ develop ]

env:
  AWS_REGION: us-east-1
  AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXTAUTH_URL }}
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Deploy to AWS Amplify
        run: |
          set -x  # Enable debug mode
          echo "Starting deployment to AWS Amplify..."
          
          echo "Creating deployment ZIP..."
          zip -r build.zip .next package.json package-lock.json public
          
          echo "Checking if branch exists..."
          if ! aws amplify get-branch --app-id $AMPLIFY_APP_ID --branch-name develop; then
            echo "Branch 'develop' doesn't exist, creating it..."
            aws amplify create-branch --app-id $AMPLIFY_APP_ID --branch-name develop
          fi
          
          echo "Creating deployment..."
          FILE_MAP='{"baseDirectory":".","files":[".next/**/*","public/**/*","package.json","package-lock.json"]}'
          DEPLOYMENT_ID=$(aws amplify create-deployment \
            --app-id $AMPLIFY_APP_ID \
            --branch-name develop \
            --file-map "$FILE_MAP" \
            --output text --query 'jobId')
            
          echo "Starting deployment with ID: $DEPLOYMENT_ID"
          aws amplify start-deployment \
            --app-id $AMPLIFY_APP_ID \
            --branch-name develop \
            --job-id $DEPLOYMENT_ID
