name: Deploy to Staging

on:
  push:
    branches: [ develop ]

env:
  AWS_REGION: us-east-1
  AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXTAUTH_URL }}
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Debug AWS Configuration
        run: |
          echo "Checking AWS Configuration:"
          aws configure list
          echo "Checking AWS Identity:"
          aws sts get-caller-identity
          echo "Checking Amplify App:"
          aws amplify get-app --app-id ${{ env.AMPLIFY_APP_ID }}
          
      - name: Deploy to AWS Amplify
        run: |
          echo "Creating deployment ZIP..."
          zip -r build.zip .next package.json package-lock.json public
          ls -la build.zip
          
          echo "Checking if branch exists..."
          aws amplify get-branch --app-id ${{ env.AMPLIFY_APP_ID }} --branch-name develop || {
            echo "Branch 'develop' doesn't exist, creating it..."
            aws amplify create-branch --app-id ${{ env.AMPLIFY_APP_ID }} --branch-name develop
          }
          
          echo "Starting deployment..."
          aws amplify start-job \
            --app-id ${{ env.AMPLIFY_APP_ID }} \
            --branch-name develop \
            --job-type RELEASE || {
            echo "Error starting job. Checking job status..."
            aws amplify list-jobs \
              --app-id ${{ env.AMPLIFY_APP_ID }} \
              --branch-name develop
          }
